# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4daf7e7a9e79f557266571e72a46ca2baa870285129c6bdeef4b0ffc89643a4cf19680918a029693b190f9d01bb0a8d83b988cb4da2b3c2acb60658c1600ee4

test:
  secret_key_base: 94028bc6f082f1d79ceb9d8a00818a6817c0d8ea762e3bab8bafc9ed3ceefc8c03b4af14e7653a74bfd66e23e8c46a167cc30d05be57db0e4cdf894524d94bc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
